use thiserror::Error;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
pub enum ErrorCode {
    #[error("invalid_utf8")]
    InvalidUtf8,
    #[error("utf8_bom_not_allowed")]
    Utf8BomNotAllowed,
    #[error("trailing_bytes")]
    TrailingBytes,
    #[error("unexpected_end")]
    UnexpectedEnd,
    #[error("unexpected_token")]
    UnexpectedToken,
    #[error("max_bytes_exceeded")]
    MaxBytesExceeded,
    #[error("max_depth_exceeded")]
    MaxDepthExceeded,
    #[error("max_fields_exceeded")]
    MaxFieldsExceeded,
    #[error("max_array_items_exceeded")]
    MaxArrayItemsExceeded,
    #[error("max_string_bytes_exceeded")]
    MaxStringBytesExceeded,
    #[error("duplicate_key")]
    DuplicateKey,
    #[error("boolean_not_allowed")]
    BooleanNotAllowed,
    #[error("invalid_number")]
    InvalidNumber,
    #[error("number_out_of_range")]
    NumberOutOfRange,
    #[error("wrong_type")]
    WrongType,
    #[error("missing_field")]
    MissingField,
    #[error("unknown_field")]
    UnknownField,
    #[error("invalid_ascii")]
    InvalidAscii,
    #[error("invalid_doc_kind")]
    InvalidDocKind,
    #[error("invalid_wire_version")]
    InvalidWireVersion,
    #[error("invalid_parent_digest")]
    InvalidParentDigest,
    #[error("invalid_sequence")]
    InvalidSequence,
    #[error("invalid_kid")]
    InvalidKid,
    #[error("invalid_base64")]
    InvalidBase64,
    #[error("invalid_spki")]
    InvalidSpki,
    #[error("invalid_signature")]
    InvalidSignature,
    #[error("invalid_quorum")]
    InvalidQuorum,
    #[error("too_many_root_keys")]
    TooManyRootKeys,
    #[error("too_many_signatures")]
    TooManySignatures,
    #[error("unsorted_array")]
    UnsortedArray,
    #[error("duplicate_array_entry")]
    DuplicateArrayEntry,
    #[error("invalid_source_id")]
    InvalidSourceId,
    #[error("invalid_release_id")]
    InvalidReleaseId,
    #[error("invalid_mcp_id")]
    InvalidMcpId,
    #[error("invalid_version")]
    InvalidVersion,
    #[error("unknown_signature_key")]
    UnknownSignatureKey,
    #[error("signature_quorum_not_met")]
    SignatureQuorumNotMet,
    #[error("bootstrap_conflict")]
    BootstrapConflict,
    #[error("missing_parent")]
    MissingParent,
    #[error("lookup_fork")]
    LookupFork,
    #[error("sequence_fork")]
    SequenceFork,
    #[error("parent_digest_mismatch")]
    ParentDigestMismatch,
    #[error("transition_violation")]
    TransitionViolation,
}

pub type Error = ErrorCode;
pub type Result<T> = std::result::Result<T, Error>;
